import React, { createContext, useContext, useEffect, useState } from 'react';

const translations = {
  EN: {
    settings: 'Settings',
    refresh: 'Refresh',
    logout: 'Logout',
    FullName: 'Full Name',
    MaBangLai: 'License No.',
    PhoneNumber: 'Phone',
    MaHocSinh: 'Student ID',
    HoTen: 'Full Name',
    Lop: 'Class',
    TinhTrang: 'Status',
    MaPhuHuynh: 'Parent ID',
    MaDiemDon: 'Pickup Point',
    licensePlate: 'License Plate',
    model: 'Model',
    speed: 'Speed (km/h)',
    managePickup: 'Manage pickup points',
    viewOnMap: 'View on map',
    vehicle: 'Vehicle',
    status: 'Status',
    Name: 'Name',
    action: 'Action',
    searchPlaceholder: 'Search...',
    english: 'EN',
    vietnamese: 'VI',
    user_off: 'OFF',
    homepage: 'Homepage',
    map: 'Map',
    student: 'Student',
    driver: 'Driver',
    route: 'Route',
    calendar: 'Calendar',
    bus: 'Bus',
    notification: 'Notification',
    cancel: 'Cancel',
    delete: 'Delete',
    confirmTitle: 'Confirm delete',
    confirmDeleteMessage: 'Are you sure you want to delete this item?',
    loading: 'Loading...',
    noData: 'No data',
    results: 'results',
    perPage: '/ page',
    save: 'Save',
    saving: 'Saving...',
    create: 'Create',
    creating: 'Creating...',
    update: 'Update',
    updating: 'Updating...',
    dashboardTitle: 'Management Dashboard',
    welcomeBack: 'Welcome back to the bus management system',
    recentStats: 'Recent Statistics',
    tripsToday: 'Trips Today',
    completed: 'Completed',
    running: 'Running',
    delayed: 'Delayed',
    totalBuses: 'Total Buses',
    totalDrivers: 'Total Drivers',
    totalRoutes: 'Total Routes',
    totalSchedules: 'Total Schedules',
    manage: 'Manage',
    driversLabel: 'Drivers',
    routesLabel: 'Routes',
    studentsLabel: 'Students',
    schedulesLabel: 'Schedules',
    activeToday: 'Active Today',
    totalStudents: 'Total Students',
    addStudent: 'Add Student',
    addBus: 'Add Bus',
    addDriver: 'Add Driver',
    addRoute: 'Add Route',
    addSchedule: 'Add Schedule',
    backToList: '← Back to list',
    addNewPoint: 'Add New Point',
    editPickupPoint: 'Edit Pickup Point',
    addPickupPoint: 'Add Pickup Point',
    points: 'points',
    routeMap: 'Route Map',
    gpsCoordinates: 'GPS Coordinates',
    filterLabel: 'Filter',
    idLabel: 'ID',
    nameLabel: 'Name',
    index: 'No.',
    pointName: 'Point Name',
    address: 'Address',
    coordinates: 'Coordinates',
    edit: 'Edit',
    close: 'Close',
    pickupPoints: 'Pickup Points',
    noPickupPoints: 'No pickup points',
    routeNotFound: 'Route not found',
    codeLabel: 'Code',
    activeStatus: 'Active',
    inactiveStatus: 'Inactive',
  },
  VI: {
    settings: 'Cài đặt',
    refresh: 'Làm mới',
    logout: 'Đăng xuất',
    FullName: 'Họ và Tên',
    MaBangLai: 'Mã Bằng Lái',
    PhoneNumber: 'Số Điện Thoại',
    MaHocSinh: 'Mã HS',
    HoTen: 'Họ Tên',
    Lop: 'Lớp',
    TinhTrang: 'Tình Trạng',
    MaPhuHuynh: 'Mã Phụ Huynh',
    MaDiemDon: 'Điểm Đón',
    licensePlate: 'Biển Số',
    model: 'Model',
    speed: 'Tốc Độ (km/h)',
    managePickup: 'Quản lý điểm đón',
    viewOnMap: 'Xem trên bản đồ',
    vehicle: 'Xe',
    status: 'Trạng Thái',
    Name: 'Tên',
    action: 'Hành Động',
    searchPlaceholder: 'Tìm kiếm...',
    english: 'EN',
    vietnamese: 'VI',
    user_off: 'TẮT',
    homepage: 'Trang chủ',
    map: 'Bản đồ',
    student: 'Học sinh',
    driver: 'Tài xế',
    route: 'Tuyến',
    calendar: 'Lịch',
    bus: 'Xe buýt',
    notification: 'Thông báo',
    cancel: 'Hủy',
    delete: 'Xóa',
    confirmTitle: 'Xác nhận xóa',
    confirmDeleteMessage: 'Bạn có chắc chắn muốn xóa mục này?',
    loading: 'Đang tải...',
    noData: 'Không có dữ liệu',
    results: 'kết quả',
    perPage: '/ trang',
    save: 'Lưu',
    saving: 'Đang lưu...',
    create: 'Tạo',
    creating: 'Đang tạo...',
    update: 'Cập Nhật',
    updating: 'Đang cập nhật...',
    dashboardTitle: 'Bảng Điều Khiển Quản Lý',
    welcomeBack: 'Chào mừng bạn quay lại hệ thống quản lý xe buýt',
    recentStats: 'Thống Kê Gần Đây',
    tripsToday: 'Chuyến Đi Hôm Nay',
    completed: 'Hoàn Thành',
    running: 'Đang Chạy',
    delayed: 'Chậm Trễ',
    totalBuses: 'Tổng Xe',
    totalDrivers: 'Tổng Tài Xế',
    totalRoutes: 'Tổng Tuyến Đường',
    totalSchedules: 'Tổng Lịch Biểu',
    manage: 'Quản Lý',
    driversLabel: 'Tài Xế',
    routesLabel: 'Tuyến Đường',
    studentsLabel: 'Học Sinh',
    schedulesLabel: 'Lịch Trình',
    activeToday: 'Hoạt Động Hôm Nay',
    totalStudents: 'Tổng Học Sinh',
    addStudent: 'Thêm Học Sinh',
    addBus: 'Thêm Xe',
    addDriver: 'Thêm Tài Xế',
    addRoute: 'Thêm Tuyến Đường',
    addSchedule: 'Thêm Lịch Biểu',
    backToList: '← Quay lại Danh sách',
    addNewPoint: 'Thêm Điểm Mới',
    editPickupPoint: 'Chỉnh Sửa Điểm Đón',
    addPickupPoint: 'Thêm Điểm Đón',
    points: 'điểm',
    routeMap: 'Bản Đồ Tuyến Đường',
    gpsCoordinates: 'Tọa Độ GPS',
    filterLabel: 'Bộ Lọc',
    idLabel: 'ID',
    nameLabel: 'Tên',
    index: 'STT',
    pointName: 'Tên Điểm',
    address: 'Địa Chỉ',
    coordinates: 'Tọa Độ',
    edit: 'Chỉnh sửa',
    close: 'Đóng',
    pickupPoints: 'Điểm Đón',
    noPickupPoints: 'Chưa có điểm đón',
    routeNotFound: 'Không tìm thấy dữ liệu tuyến',
    codeLabel: 'Mã',
    activeStatus: 'Hoạt động',
    inactiveStatus: 'Không hoạt động',
  },
};

const LanguageContext = createContext({
  lang: 'EN',
  setLang: () => {},
  t: (k) => k,
});

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(localStorage.getItem('site_lang') || 'EN');

  useEffect(() => {
    localStorage.setItem('site_lang', lang);
    try {
      window.dispatchEvent(new CustomEvent('site-language-changed', { detail: { lang } }));
    } catch (e) {
      // ignore
    }
  }, [lang]);

  const t = (key) => {
    return (translations[lang] && translations[lang][key]) || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);

export default LanguageContext;
